### ISSUE TITLE
Run OSM search for every abacq link instead of running OSM after abacq links

### ISSUE THREAD

**Issue by jamiegcan** [GoGroGlo/datasets-of-interest#1]
We're collecting `locale_1` information for every abacq link, might as well run OSM along with it so that we can fill in more data points per row.

Things to consider:
- [x] Do we do `find` or `find_all` for every OSM address? 
- `find` assumes that the 1st search result is correct, but we can never be sure about this. This also assumes one-to-one correspondence between a locale in abacq, a specific place in OSM, and a row entry. But what if there are two distinct places in a single locale (e.g., a street and a school)?
- `find_all` can allow user to confirm the address before proceeding with filling in the rows, but I'm yet to figure out how to do this. We should also be aware that having two OSM links per row can be confusing, so for now we'll assume that there can only be one OSM link/place for every row.

**Comment by GoGroGlo** [comment]
Let's try integrating OSM checks for every row being processed in `allende-scraper-test.py`:

- Default `locale_1` would be the locale parsed from abacq.
- We pass `salvador allende [country] [locale]` into a search query in OpenStreetMap [https://www.openstreetmap.org/search?query=].
- We retrieve the results list using `find_all` - each one returns an address string like this: _Residential Road Salvador Allende, Villa Victoria, Surquillo, Province of Lima, Lima Metropolitan Area, Lima, 15000, Peru_
- For every result, ask user if the address will be used to fill in the locales (effectively overriding `locale_1`). If yes, parse the address and fill in accordingly. If no, proceed to next address in OSM.
- When there are no search results in OSM, the default `locale_1` stays.

Testing is done in `openstreetmap-scraper-test.py`.

**Comment by GoGroGlo** [comment]
Testing complete - works as intended for Algeria and Peru. Up next: maybe we can add Google Maps links as well?
