### ISSUE TITLE
Collect better place types using OSM and move `type` assignment later within the script

### ISSUE THREAD

**Issue by jamiegcan** [GoGroGlo/datasets-of-interest#2]
If OSM has a result for a search query, the metadata looks like this:
`<a class="set_position" data-lat="-12.1102763" data-lon="-77.0104283" data-min-lat="-12.1103037" data-max-lat="-12.1102452" data-min-lon="-77.0109212" data-max-lon="-77.0097999" data-prefix="Residential Road" data-name="Salvador Allende, Villa Victoria, Surquillo, Province of Lima, Lima Metropolitan Area, Lima, 15000, Peru" data-type="way" data-id="426845566" href="/way/426845566">Salvador Allende, Villa Victoria, Surquillo, Province of Lima, Lima Metropolitan Area, Lima, 15000, Peru</a>`

We can make use of `data-prefix` to classify places into streets, schools, monuments, etc. We just have to find out what kinds of `data-prefix`es are possible in OSM, then add more keywords to the dictionary of lists where the `type` assignment is based from.

This requires moving the `type` assignment process later in the script so that we don't have to override what's already in the DataFrame. In effect, we would collect `type` the same way we collect `locale_2`, `locale_3`, etc.
```
    #
    # get TYPE
    # the dict used here is pretty rudimentary so this is prone to errors and needs human verification
    #
    type = ''
    for key, value in types.items():
        for type_item in value:
            if type_item in name.lower():
                type = key
    data['type'].append(type)
    print(f'Type: {type}')
```

**Comment by GoGroGlo** [comment]
Done for single-locale links.
```
    #
    # get TYPE
    # the dict used here is pretty rudimentary so this is prone to errors and needs human verification
    #
    type = ''
    # get OSM type if available
    try:
        type = re.search(r'data-prefix="(.*?)"', osm_info)
        type = str(type.group(1))
    except:
        # if not, derive it from NAME (which itself is either from OSM or the article)
        for key, value in types.items():
            for type_item in value:
                if type_item in name.lower():
                    type = key
    else:
        for key, value in types.items():
            for type_item in value:
                if type_item in type.lower():
                    type = key
    data['type'].append(type)
    print(f'Type: {type}')
```

**Comment by GoGroGlo** [comment]
Also done for multi-locale links using the same snippet. Tested to work on Algeria and Peru. 
(Bonus: I also found out that .xlsx supports Unicode and .csv doesn't, so changing the output file format to .xlsx eliminates the encoding fiascos.)
